#version 450 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout (r32f, binding = 0) uniform image2D finalHeight;
layout (r32f, binding = 1) readonly uniform image2D finalMask;

uniform float u_amplitude;

void main()
{
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

	float outputValue = imageLoad(finalMask, texelCoord).r;

    outputValue *= u_amplitude;

	imageStore(finalHeight, texelCoord, vec4(outputValue));

}