#version 450 core
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout (r32f, binding = 0) writeonly uniform image2D slopeMask;
layout (rgba16f, binding = 1) readonly uniform image2D normalMask;

void main()
{

	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

    vec3 normal = normalize(imageLoad(normalMask, coord).xyz * 2.0 - 1.0);

    float slope = 1.0 - clamp(dot(normal, vec3(0,1,0)), 0.0, 1.0);
    
    imageStore(slopeMask, coord, vec4(slope));
}
