#ifndef SRC_TERRAIN_TERRAIN_GENERATOR_H
#define SRC_TERRAIN_TERRAIN_GENERATOR_H

#include <vector>
#include <memory>
#include "graphics/texture/texture.h"
#include "graphics/shader/shader.h"
#include "graphics/shader/computeShader.h"
#include "graphics/common/GL_Types.h"

namespace pwg
{
	struct TerrainNoiseSettings;
	struct TerrainLayer;

	/**
	 * @brief Struct holding the textures generated for the terrain.
	 */
	struct TerrainTextures
	{
		std::shared_ptr<Texture> heightmap; /**< Heightmap texture generated by compute shader. */
		std::shared_ptr<Texture> normalmap; /**< Normal map texture generated from heightmap. */
		std::shared_ptr<Texture> splatmap;  /**< Splatmap texture for terrain layers/blending. */
	};

	/**
	 * @brief Handles terrain generation using compute shaders.
	 * Generates heightmaps, normal maps, and splatmaps for procedural terrain.
	 */
	class TerrainGenerator
	{
	public:

		/**
		 * @brief Constructs a TerrainGenerator with compute shaders.
		 * @param heightmapComputeShader Compute shader for generating heightmap.
		 * @param normalmapComputeShader Compute shader for generating normal map.
		 * @param splatmapComputeShader Compute shader for generating splat map.
		 */
		TerrainGenerator(
			std::shared_ptr<ComputeShader> heightmapComputeShader,
			std::shared_ptr<ComputeShader> normalmapComputeShader,
			std::shared_ptr<ComputeShader> splatmapComputeShader
		);

		/**
		 * @brief Default destructor.
		 */
		~TerrainGenerator() = default;

		/**
		 * @brief Generates terrain textures using noise settings and layers.
		 * @param noiseSettings Settings for procedural noise.
		 * @param size Size of the terrain (number of vertices per side).
		 * @param layers Terrain layers used for splatmap generation.
		 * @return Shared pointer to the generated TerrainTextures.
		 */
		std::shared_ptr<TerrainTextures> GenerateTerrain(
			TerrainNoiseSettings& noiseSettings,
			int size,
			std::vector<TerrainLayer> layers
		);

		/**
		 * @brief Returns the heightmap stored on the CPU.
		 * Useful for querying terrain height at specific coordinates.
		 */
		std::vector<float> GetCPUHeightmap();

	private:

		/**
		 * @brief Generates the heightmap texture using the compute shader.
		 */
		void GenerateHeightmap(TerrainNoiseSettings& noiseSettings);

		/**
		 * @brief Generates the normal map texture from the heightmap.
		 */
		void GenerateNormalmap(float amplitude);

		/**
		 * @brief Generates the splatmap texture using terrain layers.
		 * @param layers Terrain layers.
		 * @param amplitude Max terrain height for normalization.
		 */
		void GenerateSplatmap(std::vector<TerrainLayer> layers, float amplitude);

	private:
		std::shared_ptr<ComputeShader> m_heightmapComputeShader;	/**< Compute shader for heightmap. */
		std::shared_ptr<ComputeShader> m_normalmapComputeShader;	/**< Compute shader for normal map. */
		std::shared_ptr<ComputeShader> m_splatmapComputeShader;		/**< Compute shader for splatmap. */

		std::shared_ptr<TerrainTextures> m_textures;				/**< Generated terrain textures. */
		bool m_texturesCreated{ false };							/**< Flag indicating if textures are already generated. */

		unsigned int m_heightmapID{ 0 };							/**< OpenGL texture ID for heightmap. */
		unsigned int m_normalmapID{ 0 };							/**< OpenGL texture ID for normal map. */
		unsigned int m_splatmapID{ 0 };								/**< OpenGL texture ID for splatmap. */

		int m_size{ 0 };											/**< Terrain size (width/height in vertices). */
		std::vector<float> m_cpuHeightmap;							/**< CPU-side copy of heightmap for queries. */
	};
} // namespace pwg

#endif // !SRC_TERRAIN_TERRAIN_GENERATOR_H
